# Generated by Django 6.0.7 on 2026-08-13 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Card', 'Card'), ('Bank', 'Bank'), ('Other', 'Other')], default='UPI', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentPeriodAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_accounts', to='core.accountingperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_accounts', to='core.student')),
            ],
            options={
                'ordering': ['period__start_date', 'student__hostel_id'],
                'unique_together': {('student', 'period')},
            },
        ),
    ]
