# Generated by Django 6.0.7 on 2026-08-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_payment_method_studentperiodaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0, help_text='Total number of students in the mess')),
            ],
            options={
                'verbose_name': 'Mess Setting',
                'verbose_name_plural': 'Mess Settings',
            },
        ),
        migrations.AddField(
            model_name='studentperiodaccount',
            name='is_manual_due',
            field=models.BooleanField(default=False, help_text='Whether due is manually set'),
        ),
        migrations.AddField(
            model_name='studentperiodaccount',
            name='manual_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, overrides auto-calculated due', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
