# Generated by Django 6.0.7 on 2026-08-14 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_studentperiodaccount_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodDefaultFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_fee_per_student', models.DecimalField(decimal_places=2, help_text='Default fee per active student for this period', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_fee', to='core.accountingperiod')),
            ],
            options={
                'ordering': ['-period__start_date'],
            },
        ),
    ]
