# Generated by Django 6.0.7 on 2026-08-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_can_export_collection_excel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysettlement',
            name='accounting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='core.accountingperiod'),
        ),
        migrations.AddField(
            model_name='monthlysettlement',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlysettlement',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
