# Generated by Django 6.0.7 on 2026-08-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_monthlysettlement_accounting_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='unit',
            field=models.CharField(choices=[('Gram', 'Gram'), ('Kg', 'Kg'), ('Litre', 'Litre'), ('Packet', 'Packet'), ('Piece', 'Piece'), ('Other', 'Other')], default='Other', help_text='Unit for this purchase entry', max_length=20),
        ),
    ]
