# Generated by Django 6.0.7 on 2026-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional Gmail address for payment receipts', max_length=254),
        ),
    ]
