# Generated by Django 6.0.7 on 2026-08-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('default_fee', 'Use Default Fee'), ('custom_full', 'Custom / Full Paid Amount')], default='custom_full', help_text="Use Default Fee = apply this period's configured default fee for future calculations. Custom Full Paid = this payment amount IS the total full due.", max_length=20),
        ),
    ]
