# Generated by Django 6.0.7 on 2026-08-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_student_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
