# Generated by Django 6.0.7 on 2026-09-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional Gmail address for payment receipts', max_length=254, null=True),
        ),
    ]
