# Generated by Django 6.0.7 on 2026-09-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.CharField(blank=True, default='', help_text='e.g. Sabzi, Grocery, Dal, Masala, Dry Fruit, Dairy, Oil, Kitchen, Cleaning, Other', max_length=50),
        ),
    ]
