# Generated by Django 6.0.7 on 2026-09-21

from django.db import migrations


STOCK_ITEMS_DATA = [
    ("Tamatar", "Sabzi", "kg"),
    ("Aloo", "Sabzi", "kg"),
    ("Lal Aloo", "Sabzi", "kg"),
    ("Mircha", "Sabzi", "kg"),
    ("Matar", "Sabzi", "kg"),
    ("Pattagobhi", "Sabzi", "kg"),
    ("Shimla Mirch", "Sabzi", "kg"),
    ("Gobhi", "Sabzi", "kg"),
    ("Gajar", "Sabzi", "kg"),
    ("Dhaniya", "Sabzi", "kg"),
    ("Palak", "Sabzi", "kg"),
    ("Lahsun", "Sabzi", "kg"),
    ("Pyaz", "Sabzi", "kg"),
    ("Kohda", "Sabzi", "kg"),
    ("Boda", "Sabzi", "kg"),
    ("Chawal", "Grocery", "kg"),
    ("Atta", "Grocery", "kg"),
    ("Maida", "Grocery", "kg"),
    ("Moti Dal", "Dal", "kg"),
    ("Kabuli Chana", "Dal/Pulses", "kg"),
    ("Safed Matar", "Dal/Pulses", "kg"),
    ("Matar Dal", "Dal/Pulses", "kg"),
    ("Mungfali", "Grocery", "kg"),
    ("Jeera", "Masala", "kg"),
    ("Dhaniya Powder", "Masala", "kg"),
    ("Haldi Powder", "Masala", "kg"),
    ("Mircha Powder", "Masala", "kg"),
    ("Deggi Mirch", "Masala", "kg"),
    ("Sabji Masala", "Masala", "kg"),
    ("Meat Masala", "Masala", "kg"),
    ("Garam Masala", "Masala", "kg"),
    ("Chaat Masala", "Masala", "kg"),
    ("Aamchur", "Masala", "kg"),
    ("Laung", "Masala", "kg"),
    ("Pisa Sarso", "Masala", "kg"),
    ("Hara Namak", "Masala", "kg"),
    ("Namak", "Grocery", "kg"),
    ("Chini", "Grocery", "kg"),
    ("Chai", "Grocery", "kg"),
    ("Biscuit", "Grocery", "packet"),
    ("Namkeen", "Grocery", "packet"),
    ("Papad", "Grocery", "packet"),
    ("Pani Puri / Puri", "Grocery", "packet"),
    ("Ararot", "Grocery", "kg"),
    ("Baking Powder", "Grocery", "packet"),
    ("Kaju", "Dry Fruit", "kg"),
    ("Kishmish", "Dry Fruit", "kg"),
    ("Paneer", "Dairy", "kg"),
    ("Milk", "Dairy", "litre"),
    ("Butter", "Dairy", "kg"),
    ("Refined Oil", "Oil", "litre"),
    ("LPG Gas", "Kitchen", "kg"),
    ("Nirma Powder", "Cleaning", "kg"),
    ("Soap", "Cleaning", "piece"),
    ("Lighter", "Kitchen", "piece"),
    ("Chura", "Grocery", "kg"),
    ("Rang Gulal", "Other", "packet"),
    ("Peela Rang", "Other", "packet"),
]


CATEGORY_TO_UNIT = {
    "Sabzi": "kg",
    "Grocery": "kg",
    "Dal": "kg",
    "Dal/Pulses": "kg",
    "Masala": "kg",
    "Dry Fruit": "kg",
    "Dairy": "kg",
    "Oil": "litre",
    "Kitchen": "piece",
    "Cleaning": "kg",
    "Other": "packet",
    "Dairy": "litre",  # Milk, Butter - but note: this will be overridden by explicit unit in STOCK_ITEMS_DATA
}


def seed_stock_items(apps, schema_editor):
    StockItem = apps.get_model('core', 'StockItem')

    created = 0
    updated = 0

    for name, category, unit in STOCK_ITEMS_DATA:
        name = name.strip()
        category = category.strip()
        unit = unit.strip().lower() if unit else ''

        # Determine unit from category if not provided
        if not unit:
            unit = CATEGORY_TO_UNIT.get(category, 'kg')

        # Check if item already exists (case-insensitive name match)
        existing = StockItem.objects.filter(name__iexact=name).first()

        if existing:
            # Update existing item
            existing.category = category
            existing.unit = unit
            existing.save()
            updated += 1
        else:
            StockItem.objects.create(
                name=name,
                category=category,
                unit=unit,
                min_level=0,
            )
            created += 1

    # Log summary (visible in migration output)
    print(f"Stock items: {created} created, {updated} updated (total {len(STOCK_ITEMS_DATA)} items)")


def reverse_seed_stock_items(apps, schema_editor):
    """Reverse: delete the seeded items by name"""
    StockItem = apps.get_model('core', 'StockItem')
    names = [item[0] for item in STOCK_ITEMS_DATA]
    StockItem.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_stockitem_category'),
    ]

    operations = [
        migrations.RunPython(seed_stock_items, reverse_seed_stock_items),
    ]